/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.8).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.allianz.sd.core.api.controller;

import java.math.BigDecimal;

import com.allianz.sd.core.api.model.DataListAllResponse;
import com.allianz.sd.core.api.model.DataListResponse;
import com.allianz.sd.core.api.model.GenerationResponse;
import com.allianz.sd.core.api.model.InlineResponse200;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2019-09-01T09:31:06.877Z")

@Api(value = "datalists", description = "the datalists API")
public interface DatalistsApi {

    @ApiOperation(value = "", nickname = "datalistsAllGet", notes = "API to return all the data list Ids", response = DataListAllResponse.class, tags={ "DataList", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Success", response = DataListAllResponse.class),
        @ApiResponse(code = 202, message = "Accepted"),
        @ApiResponse(code = 400, message = "Bad Request", response = Error.class),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden Access"),
        @ApiResponse(code = 404, message = "Resource Not Found"),
        @ApiResponse(code = 406, message = "Not Acceptable"),
        @ApiResponse(code = 500, message = "Internal server error occurred"),
        @ApiResponse(code = 503, message = "Service Unavailable"),
        @ApiResponse(code = 504, message = "Gateway Timeout") })
    @RequestMapping(value = "/datalists/all",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.GET)
    @ResponseBody
    @Validated
    DataListAllResponse datalistsAllGet(@ApiParam(value = "Bearer oauth2_access_token", required = true) @RequestHeader(value = "Authorization", required = true) String authorization, @ApiParam(value = "[RFC 7231 Date/Time Formats](https://tools.ietf.org/html/rfc7231#section-7.1.1.1) - e.g : Sun, 06 Nov 1994 08:49:37 GMT ", required = true) @RequestHeader(value = "X-Date", required = true) String xDate, @ApiParam(value = "Unique request ID provided by the partner for logging and tracing transactions.", required = true) @RequestHeader(value = "X-Request-ID", required = true) String xRequestID, @ApiParam(value = "the body content type", required = true) @RequestHeader(value = "Content-Type", required = true) String contentType, @NotNull @ApiParam(value = "Device last updatetime e.g. 2018-02-27T00:00:00+0800", required = true) @Valid @RequestParam(value = "lastUpdateTime", required = true) String lastUpdateTime, @ApiParam(value = "The identifier of the partner organization") @RequestHeader(value = "X-Organization", required = false) String xOrganization, @ApiParam(value = "The identifier of the partner sub-organization") @RequestHeader(value = "X-Organization-Branch", required = false) String xOrganizationBranch, @ApiParam(value = "The identifier of the requester of the resource. The agents ID") @RequestHeader(value = "X-Organization-User", required = false) BigDecimal xOrganizationUser, @ApiParam(value = "The version of the resource") @RequestHeader(value = "X-API-Version", required = false) String xAPIVersion);


    @ApiOperation(value = "", nickname = "datalistsDatalistIdGet", notes = "API to return the data list values", response = DataListResponse.class, tags={ "DataList", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Success", response = DataListResponse.class),
        @ApiResponse(code = 202, message = "Accepted"),
        @ApiResponse(code = 400, message = "Bad Request", response = Error.class),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden Access"),
        @ApiResponse(code = 404, message = "Resource Not Found"),
        @ApiResponse(code = 406, message = "Not Acceptable"),
        @ApiResponse(code = 500, message = "Internal server error occurred"),
        @ApiResponse(code = 503, message = "Service Unavailable"),
        @ApiResponse(code = 504, message = "Gateway Timeout") })
    @RequestMapping(value = "/datalists/{datalistId}",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.GET)
    @ResponseBody
    @Validated
    DataListResponse datalistsDatalistIdGet(@ApiParam(value = "Bearer oauth2_access_token", required = true) @RequestHeader(value = "Authorization", required = true) String authorization, @ApiParam(value = "[RFC 7231 Date/Time Formats](https://tools.ietf.org/html/rfc7231#section-7.1.1.1) - e.g : Sun, 06 Nov 1994 08:49:37 GMT ", required = true) @RequestHeader(value = "X-Date", required = true) String xDate, @ApiParam(value = "Unique request ID provided by the partner for logging and tracing transactions.", required = true) @RequestHeader(value = "X-Request-ID", required = true) String xRequestID, @ApiParam(value = "the body content type", required = true) @RequestHeader(value = "Content-Type", required = true) String contentType, @ApiParam(value = "The unique datalist id to retrieve datalist corresponding to the ID", required = true) @PathVariable("datalistId") String datalistId, @ApiParam(value = "The identifier of the partner organization") @RequestHeader(value = "X-Organization", required = false) String xOrganization, @ApiParam(value = "The identifier of the partner sub-organization") @RequestHeader(value = "X-Organization-Branch", required = false) String xOrganizationBranch, @ApiParam(value = "The identifier of the requester of the resource. The agents ID") @RequestHeader(value = "X-Organization-User", required = false) BigDecimal xOrganizationUser, @ApiParam(value = "The version of the resource") @RequestHeader(value = "X-API-Version", required = false) String xAPIVersion);


    @ApiOperation(value = "", nickname = "datalistsGet", notes = "API to return all the data list Ids", response = InlineResponse200.class, tags={ "DataList", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Success", response = InlineResponse200.class),
        @ApiResponse(code = 202, message = "Accepted"),
        @ApiResponse(code = 400, message = "Bad Request", response = Error.class),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden Access"),
        @ApiResponse(code = 404, message = "Resource Not Found"),
        @ApiResponse(code = 406, message = "Not Acceptable"),
        @ApiResponse(code = 500, message = "Internal server error occurred"),
        @ApiResponse(code = 503, message = "Service Unavailable"),
        @ApiResponse(code = 504, message = "Gateway Timeout") })
    @RequestMapping(value = "/datalists",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.GET)
    @ResponseBody
    @Validated
    InlineResponse200 datalistsGet(@ApiParam(value = "Bearer oauth2_access_token", required = true) @RequestHeader(value = "Authorization", required = true) String authorization, @ApiParam(value = "[RFC 7231 Date/Time Formats](https://tools.ietf.org/html/rfc7231#section-7.1.1.1) - e.g : Sun, 06 Nov 1994 08:49:37 GMT ", required = true) @RequestHeader(value = "X-Date", required = true) String xDate, @ApiParam(value = "Unique request ID provided by the partner for logging and tracing transactions.", required = true) @RequestHeader(value = "X-Request-ID", required = true) String xRequestID, @ApiParam(value = "the body content type", required = true) @RequestHeader(value = "Content-Type", required = true) String contentType, @ApiParam(value = "The identifier of the partner organization") @RequestHeader(value = "X-Organization", required = false) String xOrganization, @ApiParam(value = "The identifier of the partner sub-organization") @RequestHeader(value = "X-Organization-Branch", required = false) String xOrganizationBranch, @ApiParam(value = "The identifier of the requester of the resource. The agents ID") @RequestHeader(value = "X-Organization-User", required = false) BigDecimal xOrganizationUser, @ApiParam(value = "The version of the resource") @RequestHeader(value = "X-API-Version", required = false) String xAPIVersion);


    @ApiOperation(value = "", nickname = "datalistsPublishPut", notes = "API to return all the data list Ids", response = GenerationResponse.class, tags={ "DataList", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Success", response = GenerationResponse.class),
        @ApiResponse(code = 202, message = "Accepted"),
        @ApiResponse(code = 400, message = "Bad Request", response = Error.class),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden Access"),
        @ApiResponse(code = 404, message = "Resource Not Found"),
        @ApiResponse(code = 406, message = "Not Acceptable"),
        @ApiResponse(code = 500, message = "Internal server error occurred"),
        @ApiResponse(code = 503, message = "Service Unavailable"),
        @ApiResponse(code = 504, message = "Gateway Timeout") })
    @RequestMapping(value = "/datalists/publish",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.PUT)
    @ResponseBody
    @Validated
    GenerationResponse datalistsPublishPut(@ApiParam(value = "[RFC 7231 Date/Time Formats](https://tools.ietf.org/html/rfc7231#section-7.1.1.1) - e.g : Sun, 06 Nov 1994 08:49:37 GMT ", required = true) @RequestHeader(value = "X-Date", required = true) String xDate, @ApiParam(value = "Unique request ID provided by the partner for logging and tracing transactions.", required = true) @RequestHeader(value = "X-Request-ID", required = true) String xRequestID, @ApiParam(value = "the body content type", required = true) @RequestHeader(value = "Content-Type", required = true) String contentType, @NotNull @ApiParam(value = "Code publishTime e.g. 2018-02-27T00:00:00+0800", required = true) @Valid @RequestParam(value = "publishTime", required = true) String publishTime, @ApiParam(value = "The identifier of the partner organization") @RequestHeader(value = "X-Organization", required = false) String xOrganization, @ApiParam(value = "The identifier of the partner sub-organization") @RequestHeader(value = "X-Organization-Branch", required = false) String xOrganizationBranch, @ApiParam(value = "The identifier of the requester of the resource. The agents ID") @RequestHeader(value = "X-Organization-User", required = false) BigDecimal xOrganizationUser, @ApiParam(value = "The version of the resource") @RequestHeader(value = "X-API-Version", required = false) String xAPIVersion);

}
