/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.8).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.allianz.sd.core.api.controller;

import java.math.BigDecimal;

import com.allianz.sd.core.api.model.SequenceIDGetResponse;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2019-09-01T09:31:06.877Z")

@Api(value = "sequenceID", description = "the sequenceID API")
public interface SequenceIDApi {

    @ApiOperation(value = "Fetch sequence ID from backend", nickname = "getSequenceID", notes = "", response = SequenceIDGetResponse.class, tags={ "ID (synch API)", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Success", response = SequenceIDGetResponse.class),
        @ApiResponse(code = 400, message = "Bad Request", response = Error.class),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden Access"),
        @ApiResponse(code = 404, message = "Resource Not Found"),
        @ApiResponse(code = 500, message = "Internal server error occurred"),
        @ApiResponse(code = 503, message = "Service Unavailable"),
        @ApiResponse(code = 504, message = "Gateway Timeout") })
    @RequestMapping(value = "/sequenceID",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.GET)
    @ResponseBody
    @Validated
    SequenceIDGetResponse getSequenceID(@ApiParam(value = "Bearer oauth2_access_token", required = true) @RequestHeader(value = "Authorization", required = true) String authorization, @ApiParam(value = "[RFC 7231 Date/Time Formats](https://tools.ietf.org/html/rfc7231#section-7.1.1.1) - e.g : Sun, 06 Nov 1994 08:49:37 GMT ", required = true) @RequestHeader(value = "X-Date", required = true) String xDate, @ApiParam(value = "Unique request ID provided by the partner for logging and tracing transactions.", required = true) @RequestHeader(value = "X-Request-ID", required = true) String xRequestID, @ApiParam(value = "the body content type", required = true) @RequestHeader(value = "Content-Type", required = true) String contentType, @NotNull @ApiParam(value = "The type of ID", required = true) @Valid @RequestParam(value = "category", required = true) String category, @NotNull @ApiParam(value = "Need how many the ID", required = true) @Valid @RequestParam(value = "idNums", required = true) BigDecimal idNums, @ApiParam(value = "The identifier of the partner organization") @RequestHeader(value = "X-Organization", required = false) String xOrganization, @ApiParam(value = "The identifier of the partner sub-organization") @RequestHeader(value = "X-Organization-Branch", required = false) String xOrganizationBranch, @ApiParam(value = "The identifier of the requester of the resource. The agents ID") @RequestHeader(value = "X-Organization-User", required = false) BigDecimal xOrganizationUser, @ApiParam(value = "The version of the resource") @RequestHeader(value = "X-API-Version", required = false) String xAPIVersion);

}
