/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.8).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.allianz.sd.core.api.controller;

import com.allianz.sd.core.api.model.VersionResponse;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2019-09-01T09:31:06.877Z")

@Api(value = "version", description = "the version API")
public interface VersionApi {

    @ApiOperation(value = "Sync S&D APP Version", nickname = "appUpdate", notes = "", response = VersionResponse.class, tags={ "App Update", })
    @ApiResponses(value = { 
        @ApiResponse(code = 202, message = "Accepted", response = VersionResponse.class),
        @ApiResponse(code = 400, message = "Bad Request", response = Error.class),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden Access"),
        @ApiResponse(code = 404, message = "Resource Not Found"),
        @ApiResponse(code = 500, message = "Internal server error occurred"),
        @ApiResponse(code = 503, message = "Service Unavailable"),
        @ApiResponse(code = 504, message = "Gateway Timeout") })
    @RequestMapping(value = "/version",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.GET)
    @ResponseBody
    @Validated
    VersionResponse appUpdate(@ApiParam(value = "Bearer oauth2_access_token", required = true) @RequestHeader(value = "Authorization", required = true) String authorization, @ApiParam(value = "[RFC 7231 Date/Time Formats](https://tools.ietf.org/html/rfc7231#section-7.1.1.1) - e.g : Sun, 06 Nov 1994 08:49:37 GMT ", required = true) @RequestHeader(value = "X-Date", required = true) String xDate, @ApiParam(value = "Unique request ID provided by the partner for logging and tracing transactions.", required = true) @RequestHeader(value = "X-Request-ID", required = true) String xRequestID, @ApiParam(value = "the body content type", required = true) @RequestHeader(value = "Content-Type", required = true) String contentType, @NotNull @ApiParam(value = "1.0", required = true) @Valid @RequestParam(value = "version", required = true) String version, @NotNull @ApiParam(value = "iOS | Android", required = true) @Valid @RequestParam(value = "DeviceSystem", required = true) String deviceSystem, @ApiParam(value = "The identifier of the partner organization") @RequestHeader(value = "X-Organization", required = false) String xOrganization, @ApiParam(value = "The identifier of the partner sub-organization") @RequestHeader(value = "X-Organization-Branch", required = false) String xOrganizationBranch, @ApiParam(value = "The version of the resource") @RequestHeader(value = "X-API-Version", required = false) String xAPIVersion);

}
